# Generated by Django 3.2.19 on 2023-06-30 00:24

import closedverse_main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
	('closedverse_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=256)),
                ('imageurl', models.ImageField(upload_to='ad/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1, max_length=3)),
                ('show', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(blank=True, default='Title', max_length=256)),
                ('message', models.TextField()),
                ('hide_date', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='MOTD/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='welcomemsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1, max_length=3)),
                ('show', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(default='Title', max_length=256)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='welcomemsg/%y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='require_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='disable_yeah',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_is',
            field=models.IntegerField(choices=[(0, "I don't know"), (1, 'Girl'), (2, 'Boy'), (3, 'Minion'), (4, 'Toaster'), (5, 'Dinosaur'), (6, 'Truck'), (7, 'Robot'), (8, 'Monkey'), (9, 'Big chungus'), (10, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatareyou',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='bg_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='c_tokens',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_addr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=closedverse_main.models.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='warned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warned_reason',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Post delete'), (1, 'Comment delete'), (2, 'User edit'), (3, 'Generate passwd reset'), (4, 'User delete'), (5, 'Image delete'), (6, 'Purge 1'), (7, 'Purge 2'), (8, 'Purge 3'), (9, 'Purge 4'), (10, 'Purge 5'), (11, 'Un-purge 1'), (12, 'Changed server settings')]),
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='icon/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, '3ds'), (2, 'wii u'), (3, 'switch'), (4, 'both'), (5, 'PC'), (6, 'Xbox'), (7, 'Playstation')], default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.CharField(blank=True, choices=[('announcements', 'main announcement community'), ('changelog', 'main changelog'), ('activity', 'Activity Feed posting community'), ('general', 'General Discussion Community')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'General'), (1, 'Game'), (2, 'Special'), (3, 'User Community'), (4, 'Hide')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='closedverse_main.post'),
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('old_nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('new_nickname', models.CharField(blank=True, max_length=64)),
                ('old_comment', models.TextField(blank=True, null=True)),
                ('new_comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaViews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
