# Generated by Django 3.2.19 on 2023-08-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0002_auto_20230629_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=uuid.uuid4, max_length=36)),
                ('used', models.BooleanField(default=False)),
                ('void', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Motd',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='by',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'ads'},
        ),
        migrations.AlterModelOptions(
            name='profilehistory',
            options={'verbose_name_plural': 'profile histories'},
        ),
        migrations.AlterModelOptions(
            name='welcomemsg',
            options={'verbose_name_plural': 'welcome messages'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='full',
        ),
        migrations.AddField(
            model_name='community',
            name='rank_needed_to_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='can_invite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='protect_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilehistory',
            name='new_nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='RedFlag',
        ),
        migrations.DeleteModel(
            name='Restriction',
        ),
        migrations.AddField(
            model_name='invites',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invites',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
